name: Daily Email Sender

# Controls when the workflow will run
on:
  schedule:
    # Runs at 1:00 AM UTC (which is 6:30 AM IST) every day
    - cron: '0 1 * * *'
  workflow_dispatch: # Allows manual triggering

# Set the environment variables from GitHub Secrets
env:
  NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
  TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
  WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
  EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script
      - name: Run daily email sender
        run: python main.py
